25.times do
  Article.create(:title => 'Lorem Ipsum', 
                 :name => 'Robert Frost', 
                 :content => "<p>Magna readymade duis swag dolor etsy. Laboris consectetur cardigan terry richardson fingerstache, photo booth you probably haven't heard of them single-origin coffee hella excepteur seitan pop-up pickled cupidatat. Ethical mlkshk 3 wolf moon post-ironic sed. DIY banksy cray, fixie consequat laborum nisi nulla. Wayfarers fanny pack vice, odd future readymade vegan fugiat lomo do mumblecore american apparel eu. Blog quis mumblecore, commodo marfa officia ennui. Beard direct trade ethnic accusamus, gastropub voluptate labore master cleanse +1 skateboard ea sapiente.</p><br /> 
				<p>Vinyl gastropub chambray pop-up mcsweeney's trust fund, mixtape put a bird on it VHS beard readymade. VHS nisi wolf selvage fingerstache, eu vice cred DIY gastropub freegan nostrud sed fap. Lo-fi before they sold out officia flexitarian sed cupidatat. Whatever sriracha helvetica carles, commodo accusamus reprehenderit. Tumblr iphone ethnic bushwick, single-origin coffee dreamcatcher whatever deserunt non in eiusmod id bicycle rights. Fingerstache mustache sint vinyl, tumblr wolf vice dreamcatcher tattooed brunch american apparel leggings quis bespoke. Single-origin coffee incididunt aesthetic artisan high life, tofu brooklyn stumptown umami VHS blog biodiesel aliqua keffiyeh.</p><br /> 
				<p>Mlkshk culpa godard PBR, odio keffiyeh bicycle rights locavore portland quinoa small batch raw denim sriracha sed. Retro bicycle rights skateboard, wolf cred sriracha viral culpa pickled echo park proident aliqua nihil. Reprehenderit delectus quinoa pickled dreamcatcher, cosby sweater nostrud banh mi ethnic. Gentrify mustache messenger bag shoreditch viral, ullamco nulla locavore polaroid commodo. Hella fugiat mollit, wolf photo booth aute truffaut seitan. Keytar ea vinyl, vero consequat semiotics dolore flexitarian. Pour-over tofu cardigan hoodie, nulla chambray post-ironic vice put a bird on it PBR labore cray tumblr pinterest placeat.</p><br /> 
				<p>Brooklyn marfa selvage, chambray nisi dolore ullamco craft beer adipisicing PBR odio tattooed. Officia seitan butcher dolor, helvetica nesciunt truffaut ullamco four loko fixie accusamus artisan. Qui id terry richardson, echo park synth pariatur excepteur seitan fingerstache street art odio art party small batch umami. Elit quinoa commodo, nihil laboris mumblecore letterpress food truck. Laboris bicycle rights scenester culpa. Eiusmod thundercats locavore, non nulla cred single-origin coffee 3 wolf moon 8-bit skateboard duis keytar seitan portland. PBR mustache authentic mcsweeney's sunt, esse pop-up dolore excepteur consectetur twee wayfarers hoodie forage.</p><br /> 
				<p>Readymade commodo eiusmod, ut deserunt lomo esse. Proident gluten-free mcsweeney's, do irony sint consequat cred nulla helvetica skateboard. Ennui readymade biodiesel, synth stumptown echo park narwhal whatever vinyl art party terry richardson assumenda pitchfork. Bespoke sint officia stumptown, VHS hella labore. Beard sustainable chambray messenger bag. Post-ironic aesthetic gastropub odd future wayfarers incididunt tofu brooklyn, put a bird on it whatever aliqua godard esse dreamcatcher. Mcsweeney's jean shorts truffaut small batch beard deserunt</p><br />")
end
